import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Main from "@/components/Main";

export const metadata: Metadata = {
  title: "Jayendra Bharti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background text-foreground h-dvh min-h-dvh w-full flex flex-col overflow-hidden">
        <ThemeProvider>
          <NavBar />
          <Main className="z-10 flex w-full flex-col items-center justify-between overflow-y-auto flex-1">
            {children}
            <Footer />
          </Main>
        </ThemeProvider>
      </body>
    </html>
  );
}
