import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Main from "@/components/Main";
import { getPayloadInstance } from "@/payload";
import isProfileComplete from "@/payload/globals/Profile/utils";
import { Button } from "@/components/ui/button";
import { ExternalLinkIcon } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Jayendra Bharti",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const payload = await getPayloadInstance();
  const profile = await payload.findGlobal({
    slug: "profile",
  });

  const profileComplete = isProfileComplete(profile);

  if (!profileComplete) {
    return (
      <html lang="en" suppressHydrationWarning>
        <body className="bg-background text-foreground h-dvh min-h-dvh w-full flex flex-col overflow-x-hidden">
          <ThemeProvider>
            <div className="flex flex-col items-center justify-center h-full gap-4">
              <h1 className="text-2xl font-bold">Profile is not complete</h1>
              <p>Please complete your profile to access the site.</p>
              <Link href="/admin">
                <Button>
                  Go to Admin Dashboard <ExternalLinkIcon />
                </Button>
              </Link>
            </div>
          </ThemeProvider>
        </body>
      </html>
    );
  }

  const settings = await payload.findGlobal({
    slug: "settings",
  });

  return (
    <html lang="en" suppressHydrationWarning className="overflow-hidden">
      <body className="bg-background text-foreground h-dvh min-h-dvh w-full flex flex-col overflow-x-hidden">
        <ThemeProvider>
          <NavBar profile={profile} settings={settings} />
          <Main className="z-10 flex w-full flex-col items-center justify-between overflow-y-auto overflow-x-hidden flex-1">
            {children}
            <Footer profile={profile} />
          </Main>
        </ThemeProvider>
      </body>
    </html>
  );
}
